### PR TITLE
feat!: remove faucet in testing runtime

### PR DESCRIPTION
**Pull request by jak-pan**
This brings a question if to bump only testing runtime or keep consistent?
- funded drip account for kubernetes testnet
- removed faucet

### CODE REVIEW

**Review by lumir-mrkva — CHANGES_REQUESTED** [review]
you have to increase version of client as well when you change chainspec and non testing runtime as well to keep them in sync

also you have to update lockfile after version bump

**Review by Roznovjak — APPROVED** [review]

**Comment by lumir-mrkva** [comment]
removal of pallet from chain spec probably isn't worth of major version change

**Comment by jak-pan** [comment]
> removal of pallet from chain spec probably isn't worth of major version change

It is a breaking change.

**Comment by lumir-mrkva** [comment]
> > removal of pallet from chain spec probably isn't worth of major version change
> 
> It is a breaking change.

of the runtime, not the client node

**Review by lumir-mrkva — APPROVED** [review]

**Pull request merged**
