### PR TITLE
fix: add missing pallet-proxy in std feature

### PR DESCRIPTION
**Pull request by apopiak**
`cargo check -p basilisk-runtime` was failing when trying to compile `pallet-proxy` and I noticed it was missing in the std feature list for the runtime.

### CODE REVIEW

**Review by enthusiastmartin — APPROVED** [review]

**Comment by apopiak** [comment]
should I bump impl_version? shouldn't need a spec_version bump AFAICT

**Comment by lumir-mrkva** [comment]
> should I bump impl_version? shouldn't need a spec_version bump AFAICT

yes, we use simple runtime versioning, any PR that changes runtime in any way has to increment spec version to ensure that we dont have 2 different runtimes with same spec

**Comment by apopiak** [comment]
so I will bump spec, then

**Comment by lumir-mrkva** [comment]
> so I will bump spec, then

we also keep the cargo version in sync with spec version and testing runtime spec version as well

**Pull request merged**
